services:
    db:
        image: postgres
        ports:
            - 5432:5432
        environment: 
            POSTGRES_USER: test
            POSTGRES_PASSWORD: root
            POSTGRES_DB: main_development